### PR TITLE
Fix CLI streaming issue and pin Windows to 0.14.6

### LINKED ISSUE #449: Unable to run `npx inngest-cli@latest dev` on Windows 11
I'm trying to start the inngest-cli dev on a Windows 11 computer. However when it tries to start I get the following error:

`
This version of C:\Users\Admin\AppData\Local\npm-cache\_npx\84e0b49cabd4122d\node_modules\inngest-cli\bin\inngest.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
`

I was able to run it just fine a few months back, but am now getting this error. Any ideas? 😸

### LINKED ISSUE #548: Getting invalid response status code: 400 in postinstall.js
**Describe the bug**
I'm doing `pnpm i -g inngest-cli@latest` and getting the following:

```
.../node_modules/inngest-cli postinstall: Error: Error downloading binary; invalid response status code: 400
.../node_modules/inngest-cli postinstall:     at C:\Users\me\AppData\Local\pnpm\global\5\.pnpm\inngest-cli@0.16.1\node_modules\inngest-cli\postinstall.js:64:23
.../node_modules/inngest-cli postinstall:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
.../node_modules/inngest-cli postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
```
 
 
This is after trying `npx inngest-cli@latest dev` with no success.
 
**Expected behavior**
I'm expecting the local dev server to start up. When that didn't work I expected the CLI to install. It appears that the artifact postinstall trying to retrieve is coming back with a bad request for some reason.

**System info**
- inngest-cli version: 0.16.1
- OS: Windows 10 Pro
- Version 22H2  - 19045.3208

### PR DESCRIPTION
**Pull request by jpwilliams**
## Description

Windows builds were failing to unpack downloaded binaries when using Node.js `>=v18.16.0` due to nodejs/node#45268. We've fixed this with a few pieces:

- Stop using [ZJONSSON/node-unzipper](https://github.com/ZJONSSON/node-unzipper) (which uses Node's zlib support) and instead use [cthackers/adm-zip](https://github.com/cthackers/adm-zip), which is a pure JS implementation.
- Added [debug](https://github.com/debug-js/debug) logging (enabled via `DEBUG=inngest:*`) to enable easier debugging with users.
- Pin Windows versions to `v0.14.6` while we resolve Windows build issues in #521 and #550, meaning `npx inngest-cli@latest` will work for Windows users again.

## Type of change (choose one)
- [ ] Chore (refactors, upgrades, etc.)
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Security fix (non-breaking change that fixes a potential vulnerability)
- [ ] Docs
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## Checklist
- [x] I've linked any associated issues to this PR.
- [x] I've tested my own changes.

## Related

- Closes #449 
- Closes #548 
- Workaround for:
  - nodejs/node#45268
  - ZJONSSON/node-unzipper#271

*[Check our Pull Request Guidelines](https://github.com/inngest/inngest/blob/main/docs/PULL_REQUEST_GUIDELINES.md)*

### CODE REVIEW

File: npm/postinstall.ts [hunk 1]
```diff
@@ -42,18 +45,36 @@ const platformMap: Partial<
...
+  /**
+   * Windows builds are currently not working past v0.14.6, so let's pin to that
+   * version here if we're on Windows.
+   */
+  if (platform.platform === "windows") {
+    debug("Windows detected; pinning to v0.14.6");
+    console.warn(
+      "Windows detected; pinning to last known working version 0.14.6"
+    );
+    version = "0.14.6";
```
Comment (djfarrelly) [inline npm/postinstall.ts:65]: I think this works for MVP, we could add something in the future that hits the open rest API endpoint (`https://api.github.com/repos/inngest/inngest/releases`) and iterates through and warns if there isn't an asset for that resource and if not, attempts to download the latest release for that platform. Definitely more work though, but could be more future proof after this hotfix.

**Review by djfarrelly — APPROVED** [review]
Great! Let's get this shipped so Windows devs can continue to use things and at least get a warning for now
